### ISSUE TITLE
OwnedByDefaultUser

### ISSUE THREAD

**Issue by blendsoft** [cybercog/laravel-ownership#11]
Could you add method for checking if model if owned by currently authorized user ?

**Comment by antonkomarev** [comment]
This feature will be available in v4:
```php
$comment->isOwnedByDefaultOwner();
```

Not using word `User` in method name because resolve logic could be overwritten in application and it will return custom type of owner model.

**Comment by antonkomarev** [comment]
Will be published with PR #14

**Comment by antonkomarev** [comment]
Released in [v4.0](https://github.com/cybercog/laravel-ownership/releases/tag/4.0.0). Upgrade to it will require to update classes and contracts namespaces.
