### ISSUE TITLE
OwnedOrFail

### ISSUE THREAD

**Issue by blendsoft** [cybercog/laravel-ownership#12]
Could you add method(s) throwing exception when not owner ?

**Comment by antonkomarev** [comment]
@blendsoft Throw exception when model don't have any owners or when exact user not an owner of it?

Could you provide usage example, please?

**Comment by antonkomarev** [comment]
You can use default `firstOrFail` method mixed with `whereOwnedBy` scope:

```php
Article::whereKey($articleId)->whereOwnedBy($user)->firstOrFail();
```

Does this help?

**Comment by antonkomarev** [comment]
Closing this issue. Feel free to continue conversation if solution proposed above didn't help.
