### ISSUE TITLE
The Model Owner Wont Link Up With The Owned Model

### ISSUE THREAD

**Issue by BenQoder** [cybercog/laravel-ownership#16]
I Get Error Saying

`{
    "message": "Type error: Argument 1 passed to App\\Brand::changeOwnerTo() must be an instance of Cog\\Contracts\\Ownership\\CanBeOwner, instance of App\\User given, called in C:\\xampp\\htdocs\\real\\haayaa\\app\\Http\\Controllers\\Auth\\RegisterController.php on line 142",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "C:\\xampp\\htdocs\\real\\haayaa\\vendor\\cybercog\\laravel-ownership\\src\\Traits\\HasMorphOwner.php",
    "line": 139,
    "trace": 
}`

**Comment by antonkomarev** [comment]
Add `Ownable` contract to your User model: https://github.com/cybercog/laravel-ownership#prepare-ownable-model-with-polymorphic-ownership

**Comment by dionysiosarvanitis** [comment]
Hi! Seems like `CanBeOwner` contract is necessary to be implemented in strict ownership too. That has to be documented as well.

**Comment by antonkomarev** [comment]
You are right, @dionysiosarvanitis. We are open for Pull Requests.

**Comment by antonkomarev** [comment]
It looks like issue was solved. Feel free to continue conversation or reopen an issue.
